<?php

namespace Roelab\GusBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JobcanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobcanRepository extends EntityRepository
{
}
